
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DBFirstEF_LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StaffLogin
{

    public int staff_id { get; set; }

    public string staff_pwd { get; set; }



    public virtual Staff Staff { get; set; }

}

}
