//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEF_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Assignment
    {
        public int section_id { get; set; }
        public int assignment_id { get; set; }
        public int studentID { get; set; }
        public Nullable<decimal> grade { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
